# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 10
  - name: Experience
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Volunteer
    url: Volunteer/
    weight: 40
  - name: Learning
    url: /#Learning
    weight: 50
  - name: Testimonials
    url: /#Testimonials
    weight: 60
  - name: Hobbies
    url: /#Hobbies
    weight: 70
